export const FixedCategories = [
  { id: "A1B2", name: "Fruits And Vegetables", color: "#A8E4A0" },
  { id: "C3D4", name: "Canned Goods", color: "#444" },
  { id: "E5F6", name: "Dairy", color: "#fffff5" },
  { id: "G7H8", name: "Meat", color: "#FF6666" },
  { id: "I9J0", name: "Fish And Seafood", color: "#99CCFF" },
  { id: "K1L2", name: "Condiments And Spices", color: "#FFCC99" },
  { id: "M3N4", name: "Snacks", color: "#FF99CC" },
  { id: "O5P6", name: "Bread And Bakery", color: "#66CCCC" },
  { id: "Q7R8", name: "Pasta And Rice", color: "#CC99FF" },
  { id: "S9T0", name: "Frozen Foods", color: "#FF6666" },
  { id: "U1V2", name: "Medicines And Personal Care", color: "#99FF99" },
  { id: "W3X4", name: "Household And Cleaning Supplies", color: "#FFCC33" },
  { id: "Y5Z6", name: "Baby Items", color: "#99CC99" },
];
